// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfBJnSAPncdqAGnTv2Cc0zCa0V_M0dXUg',
    appId: '1:495211324516:web:ca5a709d1541292ffb6b71',
    messagingSenderId: '495211324516',
    projectId: 'proyectoarmario-8b8d4',
    authDomain: 'proyectoarmario-8b8d4.firebaseapp.com',
    storageBucket: 'proyectoarmario-8b8d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYy5qzj7_xXCS4WLKgfglEP7HvuJ0aF_o',
    appId: '1:495211324516:android:3bc2275b42ea4405fb6b71',
    messagingSenderId: '495211324516',
    projectId: 'proyectoarmario-8b8d4',
    storageBucket: 'proyectoarmario-8b8d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgDi2OHZ7UVGSYwU6nee2Txsmqv_rYnx0',
    appId: '1:495211324516:ios:abefa4eb2797af22fb6b71',
    messagingSenderId: '495211324516',
    projectId: 'proyectoarmario-8b8d4',
    storageBucket: 'proyectoarmario-8b8d4.appspot.com',
    iosBundleId: 'com.example.proyectoFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgDi2OHZ7UVGSYwU6nee2Txsmqv_rYnx0',
    appId: '1:495211324516:ios:abefa4eb2797af22fb6b71',
    messagingSenderId: '495211324516',
    projectId: 'proyectoarmario-8b8d4',
    storageBucket: 'proyectoarmario-8b8d4.appspot.com',
    iosBundleId: 'com.example.proyectoFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfBJnSAPncdqAGnTv2Cc0zCa0V_M0dXUg',
    appId: '1:495211324516:web:b1633b9e343fd7d4fb6b71',
    messagingSenderId: '495211324516',
    projectId: 'proyectoarmario-8b8d4',
    authDomain: 'proyectoarmario-8b8d4.firebaseapp.com',
    storageBucket: 'proyectoarmario-8b8d4.appspot.com',
  );
}
